# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    branches: 
      only:
        - master

    docker:
      - image: circleci/php:7.0-apache-node-browsers
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "36:8b:79:7c:33:45:e8:29:46:aa:96:55:e1:0a:db:27"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan -p 20022 ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --rsh="ssh -p 20022" --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/home/${USER_NAME}/docker/
            fi